-- Scenario 1
CREATE OR REPLACE TRIGGER UpdateCustomerLastModified
BEFORE UPDATE ON Customers
FOR EACH ROW
BEGIN
    :NEW.LastModified := SYSDATE;
END;

-- Scenario 2
CREATE TABLE AuditLog (
    AuditID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    TransactionID NUMBER,
    AccountID NUMBER,
    Action VARCHAR2(20),
    AuditTimestamp DATE,
    FOREIGN KEY (TransactionID) REFERENCES Transactions(TransactionID),
    FOREIGN KEY (AccountID) REFERENCES Accounts(AccountID)
);
CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT ON Transactions
FOR EACH ROW
BEGIN
    INSERT INTO AuditLog (
        TransactionID,
        AccountID,
        Action,
        AuditTimestamp
    ) VALUES (
        :NEW.TransactionID,
        :NEW.AccountID,
        'INSERT',
        SYSDATE
    );
END;
INSERT INTO Transactions (
    TransactionID, AccountID, TransactionDate, Amount, TransactionType
) VALUES (
    1001, 1, SYSDATE, 500, 'DEPOSIT'
);  
select * from AUDITLOG;

-- Scenario 3
CREATE OR REPLACE TRIGGER CheckTransactionRules
BEFORE INSERT ON Transactions
FOR EACH ROW
DECLARE
    v_Balance NUMBER;
BEGIN
    -- Get current balance of the account
    SELECT Balance INTO v_Balance
    FROM Accounts
    WHERE AccountID = :NEW.AccountID;

    -- Check for withdrawal
    IF :NEW.TransactionType = 'WITHDRAWAL' THEN
        IF :NEW.Amount > v_Balance THEN
            RAISE_APPLICATION_ERROR(-20001, 'Withdrawal exceeds account balance.');
        END IF;
    ELSIF :NEW.TransactionType = 'DEPOSIT' THEN
        IF :NEW.Amount <= 0 THEN
            RAISE_APPLICATION_ERROR(-20002, 'Deposit amount must be positive.');
        END IF;
    ELSE
        RAISE_APPLICATION_ERROR(-20003, 'Invalid transaction type. Must be DEPOSIT or WITHDRAWAL.');
    END IF;
END;
INSERT INTO Transactions (TransactionID, AccountID, TransactionDate, Amount, TransactionType)
VALUES (2001, 1, SYSDATE, 100, 'DEPOSIT');
INSERT INTO Transactions (TransactionID, AccountID, TransactionDate, Amount, TransactionType)
VALUES (2002, 1, SYSDATE, 100000, 'WITHDRAWAL');